---
Name: seo
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripers\seo\Extensions\SEODataExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverStripers\seo\Extensions\SiteConfigExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        SEORequestProcessor: '%$SilverStripers\seo\Control\SEORequestProcessor'